---

- name: configs > Templates
  template:
    src:   "{{ item.template }}"
    dest:  "{{ elao_bind_configs_dir }}/{{ item.file }}"
    owner: root
    group: "{{ elao_bind_group }}"
    mode:  0644
  with_items: '{{ elao_bind_configs }}'
  notify:
    - bind restart
